version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      # If needed, you can add commands for dependency installation
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  base-directory: .
